### ISSUE TITLE
nodeinstall --install-alinode ^3  依赖文件名与线上不一致，导致下载文件404

### ISSUE THREAD

**Issue by zhongs** [cnpm/nodeinstall#14]
输入 `nodeinstall --install-alinode ^3  `
Error: GET http://alinode.aliyun.com/dist/new-alinode/v3.14.0/alinode-v3.14.0-win-x64.tar.gz got 404

线上路径是
http://alinode.aliyun.com/dist/new-alinode/v3.14.0/alinode-v3.14.0-darwin-x64.tar.gz

**Comment by sushujuan** [comment]
解决方案：nodeinstall 安装目录C:\Program Files\nodejs\node_modules\nodeinstall\lib\installer\installer.js文件 修改win为darwin
![image](https://user-images.githubusercontent.com/9583256/58869636-3111c800-86f1-11e9-9a8f-d8712a8eda21.png)

**Comment by gemwuu** [comment]
works for me.
