### ISSUE TITLE
Error: GET http://alinode.aliyun.com/dist/new-alinode/v5.16.3/SHASUMS256.txt got 404

### ISSUE THREAD

**Issue by dreamerblue** [cnpm/nodeinstall#15]
nodeinstall --install-alinode ^5

Error: GET http://alinode.aliyun.com/dist/new-alinode/v5.16.3/SHASUMS256.txt got 404

System: Ubuntu 18.04

**Comment by pengtikui** [comment]
+1

**Comment by fengmk2** [comment]
Can access now http://alinode.aliyun.com/dist/new-alinode/v5.16.3/SHASUMS256.txt

alt: https://npm.taobao.org/mirrors/alinode/v5.16.3/
