### ISSUE TITLE
NodeInstaller distMirrorUrl 地址302跳转，导致checksum校验不成功

### ISSUE THREAD

**Issue by xsbear** [cnpm/nodeinstall#17]
NodeInstaller 的 distMirrorUrl 地址 https://cdn.npmmirror.com/binaries/node 会跳转到https://cdn.npmmirror.com/binaries/node
返回302，导致verifyChecksum判断不成功，请修改相关配置

**Comment by qiangf811** [comment]
same issue

**Comment by qiangf811** [comment]
use  options.distUrl
eg: --install-node --distUrl=https://cdn.npmmirror.com 14.20.0

**Comment by atian25** [comment]
哪个 NodeInstaller

**Comment by qiangf811** [comment]
https://www.npmjs.com/package/nodeinstall

**Comment by gemwuu** [comment]
+ nodeinstall@0.1.5 @qiangf811 @xsbear
