### ISSUE TITLE
请求 tar.gz 地址错误

### ISSUE THREAD

**Issue by laibao101** [cnpm/nodeinstall#19]
https://github.com/cnpm/nodeinstall/blob/a463baadaed7feed15312abaa9d762b9089e53b4/lib/installer/installer.js#L67

错误:

Error: GET https://cdn.npmmirror.com/binaries/node/v16.15.1/node-v16.15.1-darwin-x86.tar.gz got 404

电脑：
mac m1 14寸

问题：
node < 16，os.arch() 返回 x64， 此时没有问题。
node >=16, os.arch() 返回 arm64， 此时就出现了上述错误。

**Comment by fengmk2** [comment]
pr welcome

**Comment by gemwuu** [comment]
fixed by pr https://github.com/cnpm/nodeinstall/pull/25
