### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by brucewar** [cnpm/nodeinstall#8]
![image](https://cloud.githubusercontent.com/assets/4013475/25943407/53251f36-3672-11e7-9f7b-e6b9c3392a04.png)

**Comment by popomore** [comment]
It seems the platform is different, I'll fix it.

https://npm.taobao.org/mirrors/node/v6.10.3/

**Comment by popomore** [comment]
I haven't tested on windows, so maybe litter buggy.
